ALTER TABLE proxy_pools ADD COLUMN IF NOT EXISTS latency_ms INTEGER DEFAULT 0;
ALTER TABLE proxy_pools ADD COLUMN IF NOT EXISTS region TEXT DEFAULT '';
ALTER TABLE proxy_pools ADD COLUMN IF NOT EXISTS last_tested_at TIMESTAMP WITH TIME ZONE;
